### ISSUE TITLE
Error compiling on Linux

### ISSUE THREAD

**Issue by mconsidine** [kmgill/solar_ha_processing#2]
Hi,
I'm trying to set your code up on a Linux Mint (Ubuntu 22) system and am running into a compile error.  Namely:
`
[...]
Compiling astral v0.3.2 (https://github.com/kmgill/astral#23563e78)
   Compiling imageproc v0.23.0
   Compiling sciimg v0.4.2
   Compiling solhat v0.5.0 (/home/matt/Downloads/solar_ha_processing)
error[E0432]: unresolved import `sciimg::image`
 --> src/mean.rs:5:32
  |
5 | use sciimg::{enums::ImageMode, image, path};
  |                                ^^^^^ no `image` in the root

error[E0432]: unresolved import `sciimg::image`
  --> src/processing.rs:10:14
   |
10 | use sciimg::{image, imagerot, path, quality};
   |              ^^^^^ no `image` in the root

error[E0432]: unresolved imports `sciimg::binfilereader`, `sciimg::image`
 --> src/ser.rs:5:14
  |
5 | ...iimg::{binfilereader::*, debayer, enums::ImageMode, image, imagebuffer};
  |           ^^^^^^^^^^^^^                                ^^^^^ no `image` in the root
  |           |
  |           could not find `binfilereader` in `sciimg`

error[E0433]: failed to resolve: use of undeclared type `Endian`
   --> src/ser.rs:138:68
    |
138 | ...h.to_string(), Endian::LittleEndian);
    |                   ^^^^^^ use of undeclared type `Endian`

error[E0433]: failed to resolve: use of undeclared type `Endian`
   --> src/ser.rs:214:60
    |

[...]
`
I'm wondering if you have an idea what this is due to?  This is using your master branch.  But I notice a second branch that seemed to carve out sciiimg.  However its dated November.

Any suggestions on how to proceed?

Many thanks,
mconsidine

**Comment by kmgill** [comment]
Hmm, may not have initialized the git submodule? In a new commit a few moments ago I got rid of that step so go ahead and do a pull and try the build again.

**Comment by mconsidine** [comment]
Thank you for that - it worked perfectly.  Do you have a .sh file that you can share to show how you processed the provided .SER file in /testdata?

My questions are idle ones - I'm a member of the Springfield Telescope Makers here in Vermont and have been working with a vintage spectrohelioscope/graph, reconstructing 2D images by aligning spectrum images.  So your workflow on this is real interest to me!

Regards,
mconsidine

**Comment by mconsidine** [comment]
Meant to say my questions are *not* idle ones ...
Still have a couple of errors that show up when running "cargo test" for example, but not when compiling or running solha against the /testdata SER file.  But I don't see why it won't work against other SER files now.
