### ISSUE TITLE
cargo "install" works but "check" doesn't?

### ISSUE THREAD

**Issue by mconsidine** [kmgill/solar_ha_processing#3]
Hi again,
I'm trying to get to a point where I can run your code against the testdata .ser file.  If I run "cargo install --path ." that seems to compile without error and executing "solha" without a parameter gives me the "USAGE" etc output.

But if I run "cargo check" I get the following 3 errors:
`
    Checking solhat v0.5.0 (/home/matt/Downloads/solar_ha_processing)
error[E0599]: no method named `expect` found for unit type `()` in the current scope
   --> src/ldcorrect.rs:121:18
    |
119 | /             corrected_output
120 | |                 .save(output_file)
121 | |                 .expect("Failed to save image");
    | |                 -^^^^^^ method not found in `()`
    | |_________________|
    | 

error[E0308]: mismatched types
  --> src/mean.rs:20:5
   |
8  |   pub fn build_mean_buffer(ser_file_path: &str) -> Result<image::Image> {
   |                                                    -------------------- expected `Result<sciimg::image::Image, anyhow::Error>` because of return type
...
20 | /     image::Image::new_with_bands(
21 | |         ser_file.image_width,
22 | |         ser_file.image_height,
23 | |         num_bands,
...  |
27 | |         },
28 | |     )
   | |_____^ expected `Result<Image, Error>`, found `Result<Image, &str>`
   |
   = note: expected enum `Result<_, anyhow::Error>`
              found enum `Result<_, &'static str>`

error[E0599]: no method named `expect` found for unit type `()` in the current scope
   --> src/processing.rs:314:41
    |
314 |             final_buffer.save(out_path).expect("Failed to save image");
    |                                         ^^^^^^ method not found in `()`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `solhat` (lib) due to 3 previous errors
`

Can you give me any tips on how to run your "tests" code against your "testdata" datasets?  I would have  thought that if "install" worked the "check" would as well.

Thanks in advance,
mconsidine

**Comment by kmgill** [comment]
To run the test suite, run `cargo test`. If you want to run solhat itself against the test data, run something like the following:
```
solha -v process -i testdata/Sun_150729.ser -o test-run.png -t 80 -l 34 -L -118 -T sun 
```
Where `solha` has options
* `-i` Input `.ser` datafile
* `-o` Output PNG image
* `-t` Threshold, pixel value for centering. I use 80 for 8 bit and 20000 for 16 bit
* `-l` for observer latitude
* `-L` for observer longitude
* `-T` for target. Currently can be either `sun` or `moon`. 
* `-d` Input dark frame ser file
* `-f` Input flat frame ser file
* `-D` Input dark flat ser file
* `-w` Crop width, in pixels
* `-H` Crop height, in pixels
* `-q` Use top n images, base on quality estimate
* `-s` Minimum quality estimate value to use for stacking
* `-S` Maximum quality estimate value to use for stacking (this is useful when you get the occasional glitch frame from your camera).
* `-n` Frame limit, use first n images of the input ser file.
* `-u` Drizzle scale, can be `1.0`, `1.5`, `2.0`, or `3.0`

**Comment by mconsidine** [comment]
Thanks for that.  "cargo test" generates the same errors.  Running solha against the /testdata SER file works fine though, fwiw...

**Comment by kmgill** [comment]
Yeah, the test fails one or two tests, mainly with a fail reader. You should be fine anyway running solha, but please let me know if you see any weird results.

**Comment by kmgill** [comment]
Also, if you want to run it on your own data (it expects `ser` files), check out the scripts in the root of the project for examples on how I run it.  I use  FireCapture and the names you  see in the script are profile names that I use in FC to capture the imagery. If you need I can record a demo

**Comment by mconsidine** [comment]
Thanks.  I've been using SharpCap, but am familiar with FC.  It looks like off of a main target folder (e.g. "Sun") you 6 or 8 folders for flats, dards, etc.  And then each of those you likely have timestamped folders that contain the set files.Is that the correct folder structure the current code expects?On Jun 18, 2023 1:23 PM, "Kevin M. Gill" ***@***.***> wrote:
Also, if you want to run it on your own data (it expects ser files), check out the scripts in the root of the project for examples on how I run it.  I use  FireCapture and the names you  see in the script are profile names that I use in FC to capture the imagery. If you need I can record a demo

**Comment by kmgill** [comment]
Yeah, that's the folder structure it expects. The script `run.sh` (Bash, so if you're on Windows, you'd run it in Windows Subsystem for Linux) is set so that all you need is that folder structure and the file `location.sh` in your `$HOME` directory (or $CWD, really) that contains your location like:
```
LOC_LATITUDE=43.2984
LOC_LONGITUDE=-72.4823
```
and execute using `/path/to/run.sh /path/to/observation/basedir`

The configuration values in the script are meant to updated when needed for your particular setup. If I ever get around to writing a GUI for this, it'll be a lot easier to use, lol.

**Comment by mconsidine** [comment]
Great thanks.  I'm on a Linux system (Mint/Ubuntu 22 jammy).  So the
command line is fine.  Never had a reason to deal with Rust before this, so
some of my questions may be due to that.

If the jet stream could now get redirected for awhile, I can try the code
out with a Lunt and ASI174 setup. Haha...

Have you posted anywhere your steps for acquiring bias, flats, darks?  What
telescope are you using?  Camera seems to be an ASI183?
