### ISSUE TITLE
Error with test on Windows 10

### ISSUE THREAD

**Issue by mconsidine** [kmgill/solar_ha_processing#4]
For what it's worth ...
- installed rustc/cargo via intructions here https://doc.rust-lang.org/cargo/getting-started/installation.html
- no issues with that.
- downloaded solar_ha_processing as a ZIP and unpacked that; no problems
- "cargo install --path ." ran with out error
- But ... "solar_ha_processing\solar_ha_processing-master>solha -v process -i testdata/Sun_150729.ser -o test-run.png -t 80 -l 34 -L -118 -T sun" generated the following error (which didn't show up on a Linux box):

`thread 'main' panicked at 'Invalid endian enum value', C:\Users\User\.cargo\git\checkouts\sciimg-5204ef4e09486be1\f01d9c1\src\binfilereader.rs:19:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: sciimg::binfilereader::Endian::from_i32
   3: solhat::ser::SerFile::load_ser
   4: solhat::processing::HaProcessing::init_new
   5: <solha::subs::process::Process as solha::subs::runnable::RunnableSubcommand>::run
   6: <hashbrown::raw::RawTable<T,A> as core::ops::drop::Drop>::drop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`
(At the command-line, I had previously executed 'set RUST_BACKTRACE=1')

Looks like this is coming from sciimg rather than solar_ha_processing??

**Comment by kmgill** [comment]
Ok. I am able to reproduce this issue and will investigate.

**Comment by kmgill** [comment]
Turns out the testdata file is corrupt anyway, going to replace

**Comment by kmgill** [comment]
Replaced the testdata file and added some error checking. Please try again against the new file

**Comment by mconsidine** [comment]
Confirming new code works, e.g. trying this from the command line in Win 10:
  solha -v process -i testdata\Sun_130540_F0001-0005.ser -o test-run.png -t 80 -l 43 -L -72 -T sun

The following also worked, though because the default folder name when I installed SharpCap on Win had a space in it, the full path needed to be wrapped in double-quotes.  Either forward- or back-slashes were accepted :
  solha -v process -i "c:\users\user\desktop\sharpcap captures\2023-06-19\capture\2023-06-19-2003_9.ser" -o test-run.png -t 80 -l 43 -L -72 -T sun

Note that a 1000 frame video will take a bit to process on a 4-core laptop :)
